PREFIX ex: <http://example.org/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
CONSTRUCT {
  ?s ontolex:isEvokedBy ?w .
  ?w a wikibase:Item;
    skos:prefLabel ?l;
    ex:hasURI ?uri;
    ex:hasID ?id .
}WHERE{
  ?s a ?type .
  FILTER(?type IN (skos:Concept,skos:ConceptScheme,skos:Collection))
  ?s skos:altLabel ?alt .
  ?d <http://localhost/ontology/data> ?data .
  ?data <http://localhost/ontology/searchinfo> ?d16 .
     ?d16 <http://localhost/ontology/search> ?label .
  FILTER(?label = ?alt)
  ?data <http://localhost/ontology/search> ?items .
  ?items <http://localhost/ontology/concepturi> ?uri.
         BIND(URI(?uri) AS ?w)
  ?items <http://localhost/ontology/id> ?id .
  ?items <http://localhost/ontology/label> ?l .
}
