prefix wd: <http://www.wikidata.org/entity/>
prefix wdt: <http://www.wikidata.org/prop/direct/>

# sparql --data wikidata-closure.nt --query _script/count-device-property-relations.rq

select ?rel (count(*) as ?count) where {
    ?device (wdt:P31|wdt:P279)* wd:Q1183543 .
    ?prop (wdt:P31|wdt:P279)* wd:Q937228 .
    ?device ?rel ?prop .
} group by ?rel order by desc(?count)