prefix wd: <http://www.wikidata.org/entity/>
prefix wdt: <http://www.wikidata.org/prop/direct/>

# sparql --data wikidata-closure.nt --query _script/count-device-device-relations.rq

select ?rel (count(*) as ?count) where {
    ?prop1 (wdt:P31|wdt:P279)* wd:Q937228 .
    ?prop2 (wdt:P31|wdt:P279)* wd:Q937228 .
    ?prop1 ?rel ?prop2 .
} group by ?rel order by desc(?count)