prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix ontolex: <http://www.w3.org/ns/lemon/ontolex#>
prefix wdt: <http://www.wikidata.org/prop/direct/>
prefix schema: <http://schema.org/>

select ?parent ?label ?count where {
  {
    select ?parent (count(*) as ?count) where {
      ?tag ontolex:evokes ?e .
      ?e wdt:P31?/wdt:P279* ?parent .
    } group by ?parent order by desc(?count)
  }

  optional {
    ?parent schema:name ?label
    filter (lang(?label) = "en")
  }
}
