prefix wd: <http://www.wikidata.org/entity/>
prefix wdt: <http://www.wikidata.org/prop/direct/>

# sparql --data wikidata-entities.nt --data wikidata-hierarchy.nt --query _script/filter-entities.rq --results "N-Triples" > wikidata-filtered-entities.nt

construct { ?e1 ?p ?e2 . }
where {
    ?e1 ?p ?e2 .
    filter not exists {
        values ?blacklist { wd:Q17334923 wd:Q17537576 wd:Q42889 wd:Q1211967 wd:Q2015382 wd:Q192581 wd:Q1781513 wd:Q12136 wd:Q2135465 }
        ?e1 (wdt:P31|wdt:P279)* ?blacklist .
    }
}