prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix wd: <http://www.wikidata.org/entity/>
prefix wdt: <http://www.wikidata.org/prop/direct/>
prefix schema: <http://schema.org/>
prefix : <http://ti.rw.fau.de/vocab#>

# sparql --data wikidata-closure.nt --data wikidata-hierarchy-reviewed-matches.nt --results "N-Triples" --query _script/filter-closure.rq > wikidata-filtered-closure.nt

# construct {
#     ?e1 ?rel ?e2 .
# }
# where {
#     # anchor entities in the graph
#     ?tag0 skos:closeMatch ?e0 .
#     ?tagn skos:closeMatch ?en .

#     # entities are reachable from one another
#     ?e0 owl:topObjectProperty+ ?en .
    
#     # some edge is on the path between the two anchors
#     ?e0 owl:topObjectProperty* ?e1 .
#     ?e1 ?rel ?e2 .
#     ?e2 owl:topObjectProperty* ?en .
# }

construct {
    ?e a :Node
} where {
    ?e (owl:topObjectProperty|^owl:topObjectProperty) ?ep .
    filter not exists {
        ?tag skos:closeMatch ?es .
        ?e (owl:topObjectProperty|^owl:topObjectProperty)+ ?es .
    }
}