PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
prefix wikibase: <http://wikiba.se/ontology#>
prefix bd: <http://www.bigdata.com/rdf#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix wdt: <http://www.wikidata.org/prop/direct/>
construct {
    ?from a rdfs:Class . ?to a rdfs:Class .
    ?from_r a rdf:Property ; schema:domainIncludes ?from ; schema:rangeIncludes ?to ; rdfs:subPropertyOf ?r .
} where {
    graph <tag:tmp> {
        ?from ?r ?to filter (strstarts(str(?r), str(wdt:))) filter (?r != wdt:P279 && ?r != wdt:P31)
    }
    bind (iri(concat(str(?from), "_", replace(str(?r), str(wdt:), ""))) as ?from_r)
}