prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix ble: <http://example.org/namespace/ble-gatt#>

# sparql --data aiop.ttl --data anp.ttl --data ble.ttl --data blp.ttl --data cgmp.ttl --data cpp.ttl --data cspc.ttl --data esp.ttl --data fmp.ttl --data ftmp.ttl --data glp.ttl --data hrp.ttl --data htp.ttl --data http\ proxy.ttl --data idp.ttl --data ips.ttl --data ipsp.ttl --data lehid.ttl --data lnp.ttl --data otp.ttl --data pasp.ttl --data plxp.ttl --data pxp.ttl --data rcp.ttl --data rscp.ttl --data scpp.ttl --data tds.ttl --data tip.ttl --data wsp.ttl --query gatt.rq > gatt.ttl

construct {
    ?c ?rel ?val .
    ?c skos:inScheme ble:
} where {
    ?c a skos:Concept ; ?rel ?val .
}